export enum GuildActionTypes {
    FETCH_GUILDS = 'FETCH_GUILDS',
    FETCH_GUILDS_SUCCESS = 'FETCH_GUILDS_SUCCESS',
    FETCH_GUILDS_FAILURE = 'FETCH_GUILDS_FAILURE',
    FETCH_GUILD = 'FETCH_GUILD',
    FETCH_GUILD_SUCCESS = 'FETCH_GUILD_SUCCESS',
    FETCH_GUILD_FAILURE = 'FETCH_GUILD_FAILURE',
    FETCH_GUILD_CHANNELS = 'FETCH_GUILD_CHANNELS',
    FETCH_GUILD_CHANNELS_SUCCESS = 'FETCH_GUILD_CHANNELS_SUCCESS',
    FETCH_GUILD_CHANNELS_FAILURE = 'FETCH_GUILD_CHANNELS_FAILURE',
    FETCH_GUILD_ROLES = 'FETCH_GUILD_ROLES',
    FETCH_GUILD_ROLES_SUCCESS = 'FETCH_GUILD_ROLES_SUCCESS',
    FETCH_GUILD_ROLES_FAILURE = 'FETCH_GUILD_ROLES_FAILURE'
}