export enum ReactRoleActionTypes {
    FETCH_REACTROLES = 'FETCH_REACTROLES',
    FETCH_REACTROLES_SUCCESS = 'FETCH_REACTROLES_SUCCESS',
    FETCH_REACTROLES_FAILURE = 'FETCH_REACTROLES_FAILURE',
    FETCH_REACTROLE = 'FETCH_REACTROLE',
    FETCH_REACTROLE_SUCCESS = 'FETCH_REACTROLE_SUCCESS',
    FETCH_REACTROLE_FAILURE = 'FETCH_REACTROLE_FAILURE'
}