export enum TriggerActionTypes {
    FETCH_TRIGGERS = 'FETCH_TRIGGERS',
    FETCH_TRIGGERS_SUCCESS = 'FETCH_TRIGGERS_SUCCESS',
    FETCH_TRIGGERS_FAILURE = 'FETCH_TRIGGERS_FAILURE',
    FETCH_TRIGGER = 'FETCH_TRIGGER',
    FETCH_TRIGGER_SUCCESS = 'FETCH_TRIGGER_SUCCESS',
    FETCH_TRIGGER_FAILURE = 'FETCH_TRIGGER_FAILURE'
}